version: '3.3'
services:
  dynamodb-local:
    command: "-jar DynamoDBLocal.jar -inMemory -sharedDb"
    image: "amazon/dynamodb-local:latest"
    container_name: dynamodb-local
    ports:
      - "8000:8000"
    network_mode: lambda-local
    container_name: dynamodb
